### ISSUE TITLE
Vectors are not Points!!!

### ISSUE THREAD

**Issue by kglebows** [RealConrad/42miniRT#45]
https://github.com/RealConrad/42miniRT/blob/2b9519f3baf04fa1e92b0659bcd46579888d7a18/src/render/viewport.c#L45-L46

If you want a point result - like the center of a pixel. You need to add a vector to the point! if you subtract a point from a vector you are gonna get a translated vector from the provided point to the same vector's end!

Change subtract into add.

**Comment by RealConrad** [comment]
Added the fix 👍
